### PR TITLE
Lift properties up one level so they show in side nav

### PR DESCRIPTION
**Pull request by razor-x**
image

### CODE REVIEW

**Comment by DebbieAtSeam** [comment]
I dunno, @razor-x... I don't love having the "Properties" title be the same heading level as the individual prop names. Also, for something like device, that would be an extremely long right-hand page menu.

**Comment by razor-x** [comment]
What if we introduced some kind of groupings and/or ordering? Having just "Properties" on the nav does not seem useful

I like having a way at a glance on the side to scan and see all the property names and jump to the one I'm looking for.

**Comment by DebbieAtSeam** [comment]
Also, has the title "Properties" been removed?

**Comment by razor-x** [comment]
Yes I removed the Properties title. There isn't anything else to document for the resource here.

**Comment by razor-x** [comment]
@DebbieAtSeam Can we give this one a try? We can always go back if we get feedback to the contrary.

**Comment by DebbieAtSeam** [comment]
@razor-x Sure. I've already noted my opinion. Let's try it and see how it looks.

**Pull request merged**
