### PR TITLE
fix: move files to match api file structure

### LINKED ISSUE #303: Create redirects for every page under `api-clients`
For every rename we do in https://github.com/seamapi/docs/issues/304, we need to add a redirect to https://github.com/seamapi/docs/blob/beta/.gitbook.yaml

For example, if we do

```diff
- * [Access Control Systems](api-clients/access-control-systems/README.md)
+ * [Access Control Systems](api-clients/acs/README.md)
-  * [Systems](api-clients/access-control-systems/systems/README.md)
+  * [Systems](api-clients/acs/systems/README.md)
-    * [List Systems](api-clients/access-control-systems/systems/list-systems.md)
+    * [List Systems](api-clients/acs/systems/list.md)
```

Then we need to add

```yaml
redirects:
  api-clients/access-control-systems: api-clients/acs/README.md
  api-clients/access-control-systems/systems: api-clients/acs/systems/README.md
  api-clients/access-control-systems/systems/list-systems: api-clients/acs/systems/list.md
```

We can then find/replace all links in the docs to point to the new files.

### PR DESCRIPTION
**Pull request by mikewuu**
closes #303

### CODE REVIEW

**Comment by mikewuu** [comment]
@razor-x I think I finally got it.

- [x] files are 1:1 to api in `seam-connect`
- [x] added redirects in gitbook for all renamed /moved files
- [x] did NOT update any other paths

Is the idea to have the files match, and setup the redirects, so when they're generated, the paths will be correct?

**Comment by razor-x** [comment]
> Is the idea to have the files match, and setup the redirects, so when they're generated, the paths will be correct?

Yes! We will incrementally replace the manual files with the generated files. We are setting things up so the "new" urls point to the "old" files by default. The old files will be incrementally removed as we replace them with the new ones/

**Review by razor-x — APPROVED** [review]
@mikewuu This looks good, but the last missing piece is the SUMMARY.md file. Gitbook uses that file as the source of truth for the canonical URLs.

So this PR closes https://github.com/seamapi/docs/issues/303 but we need the summary file (and the find/replace on all the urls) to close https://github.com/seamapi/docs/issues/304

We can still do it in two PRs :)

**Comment by mikewuu** [comment]
Wont the links be ok because of the redirects?

**Comment by razor-x** [comment]
Yes but we don't want to leave them there indefinitely. And the summary file is special, we have to update it for book structure to work

**Comment by mikewuu** [comment]
Makes sense. Ok, going to merge this first to close out #303

**Pull request merged**
